CREATE VIEW [dm].[Dátum] AS 
SELECT [DateKey] AS [Dátum kulcs]
, [AbsoluteDay] AS [Abszolút nap]
, [DayStart] AS [Nap kezdete]
, [DayEnd] AS [Nap vége]
, [DayOfWeek] AS [Hét napja]
, [DayNameHU] AS [Nap neve]
, [DayNameEN] AS [Day name]
, [DayShortNameHU] AS [Nap rövid neve]
, [DayShortNameEN] AS [Day short name]
, [DayOfYear] AS [Év napja]
, [Quarter] AS [Negyedév]
, [ISOWeek] AS [ISO hét]
, [YearMonth] AS [Év hónapja]
, [MonthNameHU] AS [Hónap név ]
, [MonthNameEN] AS [Month name]
, [MonthShortNameHU] AS [Hónap rövid név ]
, [MonthShortNameEN] AS [Month short name]
, [YearWeek] AS [Év hete]
, [YearHierarchy] AS [Év hierarchia]
, [MonthHierarchy] AS [Hónap hierarchia]
, [DayHierarchy] AS [Nap hierarchia]
, [Season] AS [Évszak]
, [Workdays] AS [Munkanap jelőlő]
, [WorkdayOfMonth] AS [Munkanap sorszáma a hónapban]
, [FiscalYear] AS [Pénzügyi év]
, [FiscalYearWeekKey] AS [Pénzügyi év hete kulcs]
FROM dm.DimDate
